### ISSUE TITLE
无法连接服务器

### ISSUE THREAD

**Issue by ElrathCurio** [quick123official/quick_redis_blog#25]
相同配置直连服务器，无安全设置，使用Redis Desktop Manager可以连接，使用该软件无法连接。
can not get db size. It may fail to connect to the redis server. Please ensure that you can connect to the redis server using redis-cli

**Comment by quick123official** [comment]
麻烦提供一下日志文件。
mac log file: /Users/${User Directory}/Library/ApplicationSupport/QuickRedis/logs/info.log

windows log file: C:\Users${User Directory}\AppData\Roaming\QuickRedis\logs\info.log

**Comment by ElrathCurio** [comment]
详情请见附件


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "quick123official/quick_redis_blog"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月6日(星期四) 晚上11:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [quick123official/quick_redis_blog] 无法连接服务器 (#25)





 
麻烦提供一下日志文件。
 mac log file: /Users/${User Directory}/Library/ApplicationSupport/QuickRedis/logs/info.log
 
windows log file: C:\Users${User Directory}\AppData\Roaming\QuickRedis\logs\info.log

**Comment by quick123official** [comment]
> 详情请见附件
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "quick123official/quick_redis_blog" ***@***.***&gt;; 发送时间:&nbsp;2021年5月6日(星期四) 晚上11:54 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [quick123official/quick_redis_blog] 无法连接服务器 (#25) 麻烦提供一下日志文件。 mac log file: /Users/${User Directory}/Library/ApplicationSupport/QuickRedis/logs/info.log windows log file: C:\Users${User Directory}\AppData\Roaming\QuickRedis\logs\info.log — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

邮件里面没有看到附件

**Comment by ElrathCurio** [comment]
[2021-02-04 16:45:02.657] [error] [cmd=readSystemConfig] error C:\Users\wdz\AppData\Roaming\QuickRedis/system_config.json Error: ENOENT: no such file or directory, open 'C:\Users\wdz\AppData\Roaming\QuickRedis/system_config.json'
&nbsp; &nbsp; at Object.openSync (fs.js:440:3)
&nbsp; &nbsp; at Object.func [as openSync] (electron/js2c/asar.js:140:31)
&nbsp; &nbsp; at Object.readFileSync (fs.js:342:35)
&nbsp; &nbsp; at Object.fs.readFileSync (electron/js2c/asar.js:542:40)
&nbsp; &nbsp; at Object.readSystemConfig (C:\Program Files (x86)\QuickRedis\resources\app.asar\build\modules\ElectronIntlUniversal.js:130:35)
&nbsp; &nbsp; at Object.init (C:\Program Files (x86)\QuickRedis\resources\app.asar\build\modules\ElectronIntlUniversal.js:17:51)
&nbsp; &nbsp; at Object.init (C:\Program Files (x86)\QuickRedis\resources\app.asar\build\modules\menu.js:6:31)
&nbsp; &nbsp; at App.createWindow (C:\Program Files (x86)\QuickRedis\resources\app.asar\build\main.js:64:56)
&nbsp; &nbsp; at App.emit (events.js:223:5)
[2021-02-04 16:45:04.057] [error] [cmd=getHostsData] error C:\Users\wdz\AppData\Roaming\QuickRedis/hosts_file.json Error: ENOENT: no such file or directory, open 'C:\Users\wdz\AppData\Roaming\QuickRedis/hosts_file.json'
&nbsp; &nbsp; at Object.openSync (fs.js:440:3)
&nbsp; &nbsp; at Object.func [as openSync] (electron/js2c/asar.js:140:31)
&nbsp; &nbsp; at Object.readFileSync (fs.js:342:35)
&nbsp; &nbsp; at Object.fs.readFileSync (electron/js2c/asar.js:542:40)
&nbsp; &nbsp; at Function.value (file:///C:/Program%20Files%20(x86)/QuickRedis/resources/app.asar/build/static/js/main.aa92e53a.chunk.js:1:167017)
&nbsp; &nbsp; at Object.getHostsData (file:///C:/Program%20Files%20(x86)/QuickRedis/resources/app.asar/build/static/js/main.aa92e53a.chunk.js:1:185955)
&nbsp; &nbsp; at Object.getHostsData (file:///C:/Program%20Files%20(x86)/QuickRedis/resources/app.asar/build/static/js/2.07bba85a.chunk.js:2:197095)
&nbsp; &nbsp; at new o (file:///C:/Program%20Files%20(x86)/QuickRedis/resources/app.asar/build/static/js/main.aa92e53a.chunk.js:1:176934)
&nbsp; &nbsp; at yi (file:///C:/Program%20Files%20(x86)/QuickRedis/resources/app.asar/build/static/js/2.07bba85a.chunk.js:2:2188220)
&nbsp; &nbsp; at ja (file:///C:/Program%20Files%20(x86)/QuickRedis/resources/app.asar/build/static/js/2.07bba85a.chunk.js:2:2205755)
[2021-02-04 16:45:04.088] [error] [cmd=readSystemConfig] error C:\Users\wdz\AppData\Roaming\QuickRedis/system_config.json Error: ENOENT: no such file or directory, open 'C:\Users\wdz\AppData\Roaming\QuickRedis/system_config.json'
&nbsp; &nbsp; at Object.openSync (fs.js:440:3)
&nbsp; &nbsp; at Object.func [as openSync] (electron/js2c/asar.js:140:31)
&nbsp; &nbsp; at Object.readFileSync (fs.js:342:35)
&nbsp; &nbsp; at Object.fs.readFileSync (electron/js2c/asar.js:542:40)
&nbsp; &nbsp; at Function.value (file:///C:/Program%20Files%20(x86)/QuickRedis/resources/app.asar/build/static/js/main.aa92e53a.chunk.js:1:187144)
&nbsp; &nbsp; at new n (file:///C:/Program%20Files%20(x86)/QuickRedis/resources/app.asar/build/static/js/main.aa92e53a.chunk.js:1:190115)
&nbsp; &nbsp; at yi (file:///C:/Program%20Files%20(x86)/QuickRedis/resources/app.asar/build/static/js/2.07bba85a.chunk.js:2:2188220)
&nbsp; &nbsp; at ja (file:///C:/Program%20Files%20(x86)/QuickRedis/resources/app.asar/build/static/js/2.07bba85a.chunk.js:2:2205755)
&nbsp; &nbsp; at gs (file:///C:/Program%20Files%20(x86)/QuickRedis/resources/app.asar/build/static/js/2.07bba85a.chunk.js:2:2244260)
&nbsp; &nbsp; at lu (file:///C:/Program%20Files%20(x86)/QuickRedis/resources/app.asar/build/static/js/2.07bba85a.chunk.js:2:2235475)
[2021-02-04 16:45:04.239] [info] [cmd=CheckUpdateService.check] folder create success. dirPath &gt;&nbsp; C:\Users\wdz\AppData\Roaming\QuickRedis/download/





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "quick123official/quick_redis_blog"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月7日(星期五) 上午10:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [quick123official/quick_redis_blog] 无法连接服务器 (#25)





  
详情请见附件
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "quick123official/quick_redis_blog" @.&gt;; 发送时间:&nbsp;2021年5月6日(星期四) 晚上11:54 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [quick123official/quick_redis_blog] 无法连接服务器 (#25) 麻烦提供一下日志文件。 mac log file: /Users/${User Directory}/Library/ApplicationSupport/QuickRedis/logs/info.log windows log file: C:\Users${User Directory}\AppData\Roaming\QuickRedis\logs\info.log — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
邮件里面没有看到附件

**Comment by xiuluodaren** [comment]
> 
> [2021-02-04 16:45:02.657] [error] [cmd=readSystemConfig] error C:\Users\wdz\AppData\Roaming\QuickRedis/system_config.json Error: ENOENT: no such file or directory, open 'C:\Users\wdz\AppData\Roaming\QuickRedis/system_config.json' &nbsp; &nbsp; at Object.openSync (fs.js:440:3) &nbsp; &nbsp; at Object.func [as openSync] (electron/js2c/asar.js:140:31) &nbsp; &nbsp; at Object.readFileSync (fs.js:342:35) &nbsp; &nbsp; at Object.fs.readFileSync (electron/js2c/asar.js:542:40) &nbsp; &nbsp; at Object.readSystemConfig (C:\Program Files (x86)\QuickRedis\resources\app.asar\build\modules\ElectronIntlUniversal.js:130:35) &nbsp; &nbsp; at Object.init (C:\Program Files (x86)\QuickRedis\resources\app.asar\build\modules\ElectronIntlUniversal.js:17:51) &nbsp; &nbsp; at Object.init (C:\Program Files (x86)\QuickRedis\resources\app.asar\build\modules\menu.js:6:31) &nbsp; &nbsp; at App.createWindow (C:\Program Files (x86)\QuickRedis\resources\app.asar\build\main.js:64:56) &nbsp; &nbsp; at App.emit (events.js:223:5) [2021-02-04 16:45:04.057] [error] [cmd=getHostsData] error C:\Users\wdz\AppData\Roaming\QuickRedis/hosts_file.json Error: ENOENT: no such file or directory, open 'C:\Users\wdz\AppData\Roaming\QuickRedis/hosts_file.json' &nbsp; &nbsp; at Object.openSync (fs.js:440:3) &nbsp; &nbsp; at Object.func [as openSync] (electron/js2c/asar.js:140:31) &nbsp; &nbsp; at Object.readFileSync (fs.js:342:35) &nbsp; &nbsp; at Object.fs.readFileSync (electron/js2c/asar.js:542:40) &nbsp; &nbsp; at Function.value (file:///C:/Program%20Files%20(x86)/QuickRedis/resources/app.asar/build/static/js/main.aa92e53a.chunk.js:1:167017) &nbsp; &nbsp; at Object.getHostsData (file:///C:/Program%20Files%20(x86)/QuickRedis/resources/app.asar/build/static/js/main.aa92e53a.chunk.js:1:185955) &nbsp; &nbsp; at Object.getHostsData (file:///C:/Program%20Files%20(x86)/QuickRedis/resources/app.asar/build/static/js/2.07bba85a.chunk.js:2:197095) &nbsp; &nbsp; at new o (file:///C:/Program%20Files%20(x86)/QuickRedis/resources/app.asar/build/static/js/main.aa92e53a.chunk.js:1:176934) &nbsp; &nbsp; at yi (file:///C:/Program%20Files%20(x86)/QuickRedis/resources/app.asar/build/static/js/2.07bba85a.chunk.js:2:2188220) &nbsp; &nbsp; at ja (file:///C:/Program%20Files%20(x86)/QuickRedis/resources/app.asar/build/static/js/2.07bba85a.chunk.js:2:2205755) [2021-02-04 16:45:04.088] [error] [cmd=readSystemConfig] error C:\Users\wdz\AppData\Roaming\QuickRedis/system_config.json Error: ENOENT: no such file or directory, open 'C:\Users\wdz\AppData\Roaming\QuickRedis/system_config.json' &nbsp; &nbsp; at Object.openSync (fs.js:440:3) &nbsp; &nbsp; at Object.func [as openSync] (electron/js2c/asar.js:140:31) &nbsp; &nbsp; at Object.readFileSync (fs.js:342:35) &nbsp; &nbsp; at Object.fs.readFileSync (electron/js2c/asar.js:542:40) &nbsp; &nbsp; at Function.value (file:///C:/Program%20Files%20(x86)/QuickRedis/resources/app.asar/build/static/js/main.aa92e53a.chunk.js:1:187144) &nbsp; &nbsp; at new n (file:///C:/Program%20Files%20(x86)/QuickRedis/resources/app.asar/build/static/js/main.aa92e53a.chunk.js:1:190115) &nbsp; &nbsp; at yi (file:///C:/Program%20Files%20(x86)/QuickRedis/resources/app.asar/build/static/js/2.07bba85a.chunk.js:2:2188220) &nbsp; &nbsp; at ja (file:///C:/Program%20Files%20(x86)/QuickRedis/resources/app.asar/build/static/js/2.07bba85a.chunk.js:2:2205755) &nbsp; &nbsp; at gs (file:///C:/Program%20Files%20(x86)/QuickRedis/resources/app.asar/build/static/js/2.07bba85a.chunk.js:2:2244260) &nbsp; &nbsp; at lu (file:///C:/Program%20Files%20(x86)/QuickRedis/resources/app.asar/build/static/js/2.07bba85a.chunk.js:2:2235475) [2021-02-04 16:45:04.239] [info] [cmd=CheckUpdateService.check] folder create success. dirPath &gt;&nbsp; C:\Users\wdz\AppData\Roaming\QuickRedis/download/
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "quick123official/quick_redis_blog" ***@***.***&gt;; 发送时间:&nbsp;2021年5月7日(星期五) 上午10:57 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [quick123official/quick_redis_blog] 无法连接服务器 (#25) 详情请见附件 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "quick123official/quick_redis_blog" @.&gt;; 发送时间:&nbsp;2021年5月6日(星期四) 晚上11:54 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [quick123official/quick_redis_blog] 无法连接服务器 (#25) 麻烦提供一下日志文件。 mac log file: /Users/${User Directory}/Library/ApplicationSupport/QuickRedis/logs/info.log windows log file: C:\Users${User Directory}\AppData\Roaming\QuickRedis\logs\info.log — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. 邮件里面没有看到附件 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

C:\Users\wdz\AppData\Roaming\QuickRedis/system_config.json  这个文件不存在,请检查相关目录权限,然后重新安装.
或者有没有安装和使用不是同一个账户的情况?

**Comment by ElrathCurio** [comment]
Interesting, reinstall works.关闭吧.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "quick123official/quick_redis_blog"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月7日(星期五) 中午11:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [quick123official/quick_redis_blog] 无法连接服务器 (#25)





  
[2021-02-04 16:45:02.657] [error] [cmd=readSystemConfig] error C:\Users\wdz\AppData\Roaming\QuickRedis/system_config.json Error: ENOENT: no such file or directory, open 'C:\Users\wdz\AppData\Roaming\QuickRedis/system_config.json' &nbsp; &nbsp; at Object.openSync (fs.js:440:3) &nbsp; &nbsp; at Object.func [as openSync] (electron/js2c/asar.js:140:31) &nbsp; &nbsp; at Object.readFileSync (fs.js:342:35) &nbsp; &nbsp; at Object.fs.readFileSync (electron/js2c/asar.js:542:40) &nbsp; &nbsp; at Object.readSystemConfig (C:\Program Files (x86)\QuickRedis\resources\app.asar\build\modules\ElectronIntlUniversal.js:130:35) &nbsp; &nbsp; at Object.init (C:\Program Files (x86)\QuickRedis\resources\app.asar\build\modules\ElectronIntlUniversal.js:17:51) &nbsp; &nbsp; at Object.init (C:\Program Files (x86)\QuickRedis\resources\app.asar\build\modules\menu.js:6:31) &nbsp; &nbsp; at App.createWindow (C:\Program Files (x86)\QuickRedis\resources\app.asar\build\main.js:64:56) &nbsp; &nbsp; at App.emit (events.js:223:5) [2021-02-04 16:45:04.057] [error] [cmd=getHostsData] error C:\Users\wdz\AppData\Roaming\QuickRedis/hosts_file.json Error: ENOENT: no such file or directory, open 'C:\Users\wdz\AppData\Roaming\QuickRedis/hosts_file.json' &nbsp; &nbsp; at Object.openSync (fs.js:440:3) &nbsp; &nbsp; at Object.func [as openSync] (electron/js2c/asar.js:140:31) &nbsp; &nbsp; at Object.readFileSync (fs.js:342:35) &nbsp; &nbsp; at Object.fs.readFileSync (electron/js2c/asar.js:542:40) &nbsp; &nbsp; at Function.value (file:///C:/Program%20Files%20(x86)/QuickRedis/resources/app.asar/build/static/js/main.aa92e53a.chunk.js:1:167017) &nbsp; &nbsp; at Object.getHostsData (file:///C:/Program%20Files%20(x86)/QuickRedis/resources/app.asar/build/static/js/main.aa92e53a.chunk.js:1:185955) &nbsp; &nbsp; at Object.getHostsData (file:///C:/Program%20Files%20(x86)/QuickRedis/resources/app.asar/build/static/js/2.07bba85a.chunk.js:2:197095) &nbsp; &nbsp; at new o (file:///C:/Program%20Files%20(x86)/QuickRedis/resources/app.asar/build/static/js/main.aa92e53a.chunk.js:1:176934) &nbsp; &nbsp; at yi (file:///C:/Program%20Files%20(x86)/QuickRedis/resources/app.asar/build/static/js/2.07bba85a.chunk.js:2:2188220) &nbsp; &nbsp; at ja (file:///C:/Program%20Files%20(x86)/QuickRedis/resources/app.asar/build/static/js/2.07bba85a.chunk.js:2:2205755) [2021-02-04 16:45:04.088] [error] [cmd=readSystemConfig] error C:\Users\wdz\AppData\Roaming\QuickRedis/system_config.json Error: ENOENT: no such file or directory, open 'C:\Users\wdz\AppData\Roaming\QuickRedis/system_config.json' &nbsp; &nbsp; at Object.openSync (fs.js:440:3) &nbsp; &nbsp; at Object.func [as openSync] (electron/js2c/asar.js:140:31) &nbsp; &nbsp; at Object.readFileSync (fs.js:342:35) &nbsp; &nbsp; at Object.fs.readFileSync (electron/js2c/asar.js:542:40) &nbsp; &nbsp; at Function.value (file:///C:/Program%20Files%20(x86)/QuickRedis/resources/app.asar/build/static/js/main.aa92e53a.chunk.js:1:187144) &nbsp; &nbsp; at new n (file:///C:/Program%20Files%20(x86)/QuickRedis/resources/app.asar/build/static/js/main.aa92e53a.chunk.js:1:190115) &nbsp; &nbsp; at yi (file:///C:/Program%20Files%20(x86)/QuickRedis/resources/app.asar/build/static/js/2.07bba85a.chunk.js:2:2188220) &nbsp; &nbsp; at ja (file:///C:/Program%20Files%20(x86)/QuickRedis/resources/app.asar/build/static/js/2.07bba85a.chunk.js:2:2205755) &nbsp; &nbsp; at gs (file:///C:/Program%20Files%20(x86)/QuickRedis/resources/app.asar/build/static/js/2.07bba85a.chunk.js:2:2244260) &nbsp; &nbsp; at lu (file:///C:/Program%20Files%20(x86)/QuickRedis/resources/app.asar/build/static/js/2.07bba85a.chunk.js:2:2235475) [2021-02-04 16:45:04.239] [info] [cmd=CheckUpdateService.check] folder create success. dirPath &gt;&nbsp; C:\Users\wdz\AppData\Roaming\QuickRedis/download/
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "quick123official/quick_redis_blog" @.&gt;; 发送时间:&nbsp;2021年5月7日(星期五) 上午10:57 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [quick123official/quick_redis_blog] 无法连接服务器 (#25) 详情请见附件 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "quick123official/quick_redis_blog" @.&gt;; 发送时间:&nbsp;2021年5月6日(星期四) 晚上11:54 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [quick123official/quick_redis_blog] 无法连接服务器 (#25) 麻烦提供一下日志文件。 mac log file: /Users/${User Directory}/Library/ApplicationSupport/QuickRedis/logs/info.log windows log file: C:\Users${User Directory}\AppData\Roaming\QuickRedis\logs\info.log — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. 邮件里面没有看到附件 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
C:\Users\wdz\AppData\Roaming\QuickRedis/system_config.json  这个文件不存在,请检查相关目录权限,然后重新安装.
